version: 2

sources:
  - name: dwh
    database: dwh
    schema: pactravel
    tables:
      - name: aircrafts
      - name: airlines
      - name: airports
      - name: customers
      - name: hotels
      - name: flight_bookings
      - name: hotel_bookings
