name: 'dbt_transform'
version: '1.0.0'

profile: 'dbt_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_transform:
    # Konfigurasi default untuk semua model
    +materialized: table
    +persist_docs:
      relation: true
      columns: true
    +on_schema_change: "sync_all_columns"

    mart:
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
      +on_schema_change: "sync_all_columns"

seeds:
  dbt_transform:
    +persist_docs:
      relation: true
      columns: true
    +on_schema_change: "sync_all_columns"

snapshots:
  dbt_transform:
    +persist_docs:
      relation: true
      columns: true
    +on_schema_change: "sync_all_columns"

vars:
  'dbt_date:time_zone': 'Asia/Jakarta'